// Login
export const STORE_USER = 'store_user';
export const LOGIN_LOADING = 'toggle_login_loading';
export const FETCH_LOGIN_BEGIN = 'FETCH_LOGIN_BEGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL = 'FETCH_LOGIN_FAIL';
// My Account
export const SAVE_ACCOUNT_ID = "SAVE_ACCOUNT_ID";
export const SAVE_PREMISE_ADDRESS = "SAVE_PREMISE_ADDRESS";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_OLD_DETAILS = "FETCH_USER_OLD_DETAILS";
export const FETCH_EDIT_SECURITY_QUESTIONS = "FETCH_EDIT_SECURITY_QUESTIONS";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_LATEST_BILL = "FETCH_LATEST_BILL";
export const FETCH_CONSUMPTION_DETAILS = "FETCH_CONSUMPTION_DETAILS";
export const FETCH_BILL_LIST = "FETCH_BILL_LIST";
export const FETCH_SURVEY_LIST = "FETCH_SURVEY_LIST";
export const SAVE_VIEW_BILL_DATA = "SAVE_VIEW_BILL_DATA";
export const SAVE_ORDER_DATA = "SAVE_ORDER_DATA";
export const FETCH_PAYMENT_HISTORY_LIST = "FETCH_PAYMENT_HISTORY_LIST";
