//LOGIN
  //MANUAL
  export const LOGIN_PAGE = 'VIEW: LOGIN_PAGE';

  export const LOGIN_SUCCESS = 'RESPONSE: MANUAL_LOGIN_SUCCESS';
  export const LOGIN_FAIL = 'RESPONSE: MANUAL_LOGIN_FAIL';
  export const LOGIN_ERROR = 'RESPONSE: MANUAL_LOGIN_ERROR';

  //GMAIL
  export const GMAIL_LOGIN = 'TAPPED: GMAIL_LOGIN';
  export const GMAIL_SIGNIN_SUCCESS = 'RESPONSE: GMAIL_SIGNIN_SUCCESS';
  export const GMAIL_SIGNIN_FAIL = 'RESPONSE: GMAIL_SIGNIN_FAIL';
  export const GMAIL_SIGNIN_ERROR = 'RESPONSE: GMAIL_SIGNIN_ERROR';

  //GET USER INFO (GMAIL SIGN)
  export const GET_USER_INFO_VIA_EMAIL_SUCCESS = 'RESPONSE: GET_USER_INFO_VIA_EMAIL_SUCCESS';
  export const GET_USER_INFO_VIA_EMAIL_FAIL = 'RESPONSE: GET_USER_INFO_VIA_EMAIL_FAIL';
  export const GET_USER_INFO_VIA_EMAIL_ERROR = 'RESPONSE: GET_USER_INFO_VIA_EMAIL_ERROR';

  // GET PLAN TYPE AND IF USER EXIST (GMAIL SIGNIN)
  export const GET_PLANTYPE_USEREXIST_SUCCESS = 'RESPONSE: GET_PLANTYPE_USEREXIST_SUCCESS';
  export const GET_PLANTYPE_USEREXIST_FAIL = 'RESPONSE: GET_PLANTYPE_USEREXIST_FAIL';
  export const GET_PLANTYPE_USEREXIST_ERROR = 'RESPONSE: GET_PLANTYPE_USEREXIST_ERROR';
  
//LEADS PAGE
  export const LEADS_PAGE = 'VIEW: LEADS_PAGE';
  export const ADD_LEAD_PAGE = 'VIEW: ADD_LEAD_PAGE';
  export const EDIT_LEAD_PAGE = 'VIEW: EDIT_LEAD_PAGE';

//LEAD RECORD PAGE
  export const LEAD_RECORD_PAGE = 'VIEW: LEAD_RECORD_PAGE';
  export const DUPLICATE_LEAD_PAGE = 'VIEW: DUPLICATE_LEAD_PAGE';

//LEAD ACTIVITIES
  export const LEAD_ACTIVITIES_PAGE = 'VIEW: LEAD_ACTIVITIES_PAGE';

//NOTIFICATION PAGE
  export const NOTIFICATION_LIST_PAGE = 'VIEW: NOTIFICATION_LIST_PAGE';

//OPPORTUNITIES PAGE
  export const OPPORTUNITY_PAGE = 'VIEW: OPPORTUNITY_PAGE';
  export const OPPORTUNITY_LEADS_PAGE = 'VIEW: OPPORTUNITY_LEADS_PAGE';
  export const ADD_OPPORTUNITY_PAGE = 'VIEW: ADD_OPPORTUNITY_PAGE';
  export const UPDATE_OPPORTUNITY_PAGE = 'VIEW: UPDATE_OPPORTUNITY_PAGE';
  export const ADD_OPPORTUNITY_MODAL_PAGE = 'VIEW: ADD_OPPORTUNITY_MODAL_PAGE';

//SEND EMAIL & SMS PAGE
  export const SEND_EMAIL_PAGE = 'VIEW: SEND_EMAIL_PAGE';
  export const SEND_SMS_PAGE = 'VIEW: SEND_SMS_PAGE';

//ADD TASK & NOTE PAGE
  export const ADD_TASK_PAGE = 'VIEW: ADD_TASK_PAGE';
  export const ADD_NOTE_PAGE = 'VIEW: ADD_NOTE_PAGE';

//DASHBOARD PAGE
  export const DASHBOARD_PAGE = 'VIEW: DASHBOARD_PAGE';

//USER PERSONAL ANALYTICS PAGE
  export const USER_ANALYTICS_ACTIVITY_PAGE = 'VIEW: USER_ANALYTICS_ACTIVITY_PAGE';
  export const USER_ANALYTICS_EMAIL_PAGE = 'VIEW: USER_ANALYTICS_EMAIL_PAGE';
  export const USER_ANALYTICS_SMS_PAGE = 'VIEW: USER_ANALYTICS_SMS_PAGE';

//ENTERPRISE ANALYTICS PAGE
  export const ENTERPRISE_ANALYTICS_ACTIVITY_PAGE = 'VIEW: ENTERPRISE_ANALYTICS_ACTIVITY_PAGE';
  export const ENTERPRISE_ANALYTICS_EMAIL_PAGE = 'VIEW: ENTERPRISE_ANALYTICS_EMAIL_PAGE';
  export const ENTERPRISE_ANALYTICS_SMS_PAGE = 'VIEW: ENTERPRISE_ANALYTICS_SMS_PAGE';

//SEGMENTS PAGE
  export const SEGMENTS_PAGE = 'VIEW: SEGMENTS_PAGE';

//ACCOUNT SETTINGS
  export const ACCOUNT_SETTINGS_PAGE = 'VIEW: ACCOUNT_SETTINGS_PAGE';